
-- Retail Sales Analysis SQL Project

CREATE DATABASE sql_project_p2;
DROP TABLE IF EXISTS retail_sales;

CREATE TABLE retail_sales
(
    transaction_id INT PRIMARY KEY,
    sale_date DATE,
    sale_time TIME,
    customer_id INT,
    gender VARCHAR(15),
    age INT,
    category VARCHAR(20),
    quantity INT,
    price_per_unit NUMERIC(10,2),
    cogs NUMERIC(10,2),
    total_sale NUMERIC(10,2)
);


SELECT *
FROM retail_sales
LIMIT 10;

SELECT COUNT(*) AS total_records
FROM retail_sales;



SELECT *
FROM retail_sales
WHERE transaction_id IS NULL;

SELECT *
FROM retail_sales
WHERE sale_date IS NULL;

SELECT *
FROM retail_sales
WHERE sale_time IS NULL;

SELECT *
FROM retail_sales
WHERE transaction_id IS NULL
   OR sale_date IS NULL
   OR sale_time IS NULL
   OR customer_id IS NULL
   OR gender IS NULL
   OR age IS NULL
   OR category IS NULL
   OR quantity IS NULL
   OR price_per_unit IS NULL
   OR cogs IS NULL
   OR total_sale IS NULL;

DELETE
FROM retail_sales
WHERE transaction_id IS NULL
   OR sale_date IS NULL
   OR sale_time IS NULL
   OR customer_id IS NULL
   OR gender IS NULL
   OR age IS NULL
   OR category IS NULL
   OR quantity IS NULL
   OR price_per_unit IS NULL
   OR cogs IS NULL
   OR total_sale IS NULL;


-- Total Sales Records

SELECT COUNT(*) AS total_sales
FROM retail_sales;

-- Total Customers

SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM retail_sales;

-- Categories

SELECT DISTINCT category
FROM retail_sales;

-- Data Analysis & Business Key Problems & Answers

-- My Analysis & Findings

-- Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05
-- Q.2 Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 10 in the month of Nov-2022
-- Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.
-- Q.4 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.
-- Q.5 Write a SQL query to find all transactions where the total_sale is greater than 1000.
-- Q.6 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
-- Q.7 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year
-- Q.8 Write a SQL query to find the top 5 customers based on the highest total sales 
-- Q.9 Write a SQL query to find the number of unique customers who purchased items from each category.
-- Q.10 Write a SQL query to create each shift and number of orders (Example Morning <=12, Afternoon Between 12 & 17, Evening >17)
-- Q.11 Write a SQL query to calculate total revenue generated by each gender
-- Q.12 Write a SQL query to find total revenue generated by each age group
-- Q.13 Write a SQL query to find the busiest shopping hour
-- Q.14 Write a SQL query to find monthly revenue
-- Q.15 Write a SQL query to Find average order value

-- Q1
-- Sales on 2022-11-05

SELECT *
FROM retail_sales
WHERE sale_date='2022-11-05';



-- Q2
-- Clothing sales in November 2022
-- Quantity >= 4

SELECT *
FROM retail_sales
WHERE category='Clothing'
AND TO_CHAR(sale_date,'YYYY-MM')='2022-11'
AND quantity>=4;


-- Q3
-- Total Sales by Category

SELECT
category,
SUM(total_sale) AS net_sales,
COUNT(*) AS total_orders
FROM retail_sales
GROUP BY category
ORDER BY net_sales DESC;


-- Q4
-- Average Age of Beauty Customers

SELECT
ROUND(AVG(age),2) AS average_age
FROM retail_sales
WHERE category='Beauty';



-- Q5
-- Sales greater than 1000

SELECT *
FROM retail_sales
WHERE total_sale>1000;


-- Q6
-- Transactions by Gender & Category

SELECT
category,
gender,
COUNT(transaction_id) AS total_transactions
FROM retail_sales
GROUP BY category,gender
ORDER BY category,gender;


-- Q7
-- Best Selling Month Each Year

SELECT
year,
month,
avg_sale
FROM
(
SELECT
EXTRACT(YEAR FROM sale_date) AS year,
EXTRACT(MONTH FROM sale_date) AS month,
AVG(total_sale) AS avg_sale,
RANK() OVER
(
PARTITION BY EXTRACT(YEAR FROM sale_date)
ORDER BY AVG(total_sale) DESC
) AS ranking

FROM retail_sales
GROUP BY
EXTRACT(YEAR FROM sale_date),
EXTRACT(MONTH FROM sale_date)

) 
WHERE ranking=1;


-- Q8
-- Top 5 Customers

SELECT

customer_id,
SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY customer_id
ORDER BY total_sales DESC
LIMIT 5;

-- Q9
-- Unique Customers per Category

SELECT
category,
COUNT(DISTINCT customer_id) AS unique_customers
FROM retail_sales
GROUP BY category
ORDER BY unique_customers DESC;


-- Q10
-- Orders by Shift

WITH hourly_sales AS
(

SELECT
*,
CASE
WHEN EXTRACT(HOUR FROM sale_time)<12
THEN 'Morning'
WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17
THEN 'Afternoon'
ELSE 'Evening'
END AS shift
FROM retail_sales

)

SELECT
shift,
COUNT(*) AS total_orders
FROM hourly_sales
GROUP BY shift
ORDER BY total_orders DESC;

-- Q11
-- Calculate total revenue generated by each gender.

SELECT
    gender,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY gender
ORDER BY total_revenue DESC;


-- Q12
-- Find total revenue generated by each age group.

SELECT
CASE
    WHEN age BETWEEN 18 AND 25 THEN '18-25'
    WHEN age BETWEEN 26 AND 35 THEN '26-35'
    WHEN age BETWEEN 36 AND 45 THEN '36-45'
    ELSE '46+'
END AS age_group,
SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q13
-- Find the busiest shopping hour.

SELECT
EXTRACT(HOUR FROM sale_time) AS shopping_hour,
COUNT(*) AS total_orders
FROM retail_sales
GROUP BY shopping_hour
ORDER BY total_orders DESC;

-- Q14
-- Find monthly revenue

SELECT

DATE_TRUNC('month',sale_date) AS month,
SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY month
ORDER BY month;

-- Q15
-- Find average order value

SELECT
ROUND(AVG(total_sale),2) AS average_order_value
FROM retail_sales;

-- END OF PROJECT